version: "3.8"
services:
  web:
    build: .
    volumes:
      - ./src:/usr/src/createx/src
      - web-static:/usr/src/createx/static
      - web-media:/usr/src/createx/src/media
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  nginx:
    image: nginx:1.25
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - web-static:/static/
      - web-media:/media/
    depends_on:
      - web


volumes:
  postgres-data:
  web-static:
  web-media:
