apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tex-engine.deployment.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas:  {{ .Values.tex_engine.replicas }}
  selector:
    matchLabels: {{ include "tex-engine.labels" . | nindent 6 }}
  template:
    metadata:
      labels: {{ include "tex-engine.labels" . | nindent 10 }}
    spec:
      containers:
        - name: "tex-engine"
          image: {{ .Values.tex_engine.imageName }}:{{ .Values.tex_engine.imageTag }}
          ports:
            - containerPort: {{ include "tex-engine.port" . }}
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"
