apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "createx.pvc.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.createx.mediaStorageSize }}
