{{- $djangoSecret := .Values.createx.settings.djangoSecret | default (randAlphaNum 36) | b64enc | quote }}

{{- if not .Values.createx.settings.djangoSecret }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "secret.name" .)) }}
  {{- if $secretObj }}
    {{- $djangoSecret = (get $secretObj "stringData") }}
  {{- end -}}
{{- end -}}

{{- $superuserPassword := .Values.createx.adminUser.password | default (randAlphaNum 24) | b64enc | quote }}

{{- if not .Values.createx.adminUser.password }}
  {{- $secretObj := (lookup "v1" "Secret" .Release.Namespace (include "secret.name" .)) }}
  {{- if $secretObj }}
    {{- $superuserPassword = (get $secretObj "stringData") }}
  {{- end -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "secret.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  DJANGO_SECRET: {{ $djangoSecret }}
  DJANGO_SUPERUSER_PASSWORD: {{ $superuserPassword }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.postgresPassword }}
