apiVersion: v1
kind: Service
metadata:
  name: {{ include "tex-engine.service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.tex_engine.appName }}
  ports:
    - protocol: TCP
      port: {{ include "tex-engine.port" . }}
      targetPort: {{ include "tex-engine.port" . }}