apiVersion: v1
kind: Service
metadata:
  name: {{ include "createx.service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: {{ .Values.createx.appName }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ include "createx.port" . }}
