# Generated by Django 4.2.6 on 2023-11-10 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texdraft',
            name='tex_draft_file',
            field=models.FileField(blank=True, null=True, upload_to='tex_drafts'),
        ),
    ]
