# Generated by Django 4.2.7 on 2024-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_texdraft_tex_draft_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='texdraft',
            name='finalized',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='draftfield',
            name='jinja_variable',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='draftfield',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
