# Generated by Django 5.0.3 on 2024-03-14 16:14

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_tex_draft_first_page_texdraft_first_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitation_code', models.CharField(default=main.models.generate_random_invitation_code, max_length=12)),
                ('user_name', models.CharField(blank=True, max_length=250)),
                ('user_lang', models.CharField(default='en', max_length=2)),
            ],
        ),
    ]
