# Generated by Django 5.0.3 on 2024-03-14 16:19

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_registrationinvitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationinvitation',
            name='invitation_code',
            field=models.CharField(default=main.models.generate_random_invitation_code, max_length=12, unique=True),
        ),
    ]
