name: Docker Build and Push

on:
  push:
    tags:
      - 'v([0-9]+)\.([0-9]+)\.([0-9]+)(-(a|b|rc)\.\d+)?'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          build-args: APP_VERSION=${{ github.ref_name }}
          push: true
          tags: |
            al3nka/createx:${{ github.ref_name }}
            al3nka/createx:latest